
java:
  runtime:
    version: 11
    
spring:
  application:
    name: my-wallet-api
  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    url: jdbc:postgresql://localhost:5432/postgres?sslmode=disable #${db_Database_url} #
    username:  postgres # ${db_User} #
    password:  welcome1 # ${db_Password} #
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:  
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time-zone: Asia/Jakarta
    show-sql: true

limitActivity: 10

jwt-key:
  secret:  ${jwt-key-secret} #
  expirationMs: ${jwt-key-expirationMs}
  refreshExp : ${jwt-key-refreshExp}