
java:
  runtime:
    version: 11
    
spring:
  application:
    name: my-wallet-api
  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    url: ${db_Database_url:jdbc:postgresql://localhost:5432/postgres?sslmode=disable} #jdbc:postgresql://localhost:5432/postgres?sslmode=disable #
    username:  ${db_User:postgres} #postgres #
    password:  ${db_Password:welcome1} #welcome1 #
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:  
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time-zone: Asia/Jakarta
    show-sql: true


#limitActivity: 10

jwt-key:
  secret:  ${jwt-key-secret:mcputro} #mcputro #
  expirationMs: ${jwt-key-expirationMs:1800000} #1800000 #30menit #300000 #5menit  #
  refreshExp : ${jwt-key-refreshExp:604800000} #600000 #10menit #604800000 #7hari #